export const CONSTANTS = {
  DATABASE_HOST: 'DATABASE_HOST',
  DATABASE_USER: 'DATABASE_USER',
  DATABASE_PASSWORD: 'DATABASE_PASSWORD',
  DATABASE_NAME: 'DATABASE_NAME',
  JWT_SECRET: 'JWT_SECRET',
  DATABASE_URL: 'DATABASE_URL',
  JWT_STRATEGY: 'JWT_STRATEGY',
  GOOGLE_STRATEGY: 'GOOGLE_STRATEGY',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET'
}